name: Build and push image to docker hub
on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-rc-*'
      - 'v*.*.*-beta-*'
jobs:
  build: 
    runs-on: ubuntu-20.04
    steps:
    - name: set var
      id: setVar
      run: |
        echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
        echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/*/})" >> $GITHUB_ENV
    - uses: actions/checkout@v2
      with:
        ref: ${{ steps.setVar.outputs.TAG }}
    - name: Login
      run: |
        echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build and push
      run: |
        version=${{ steps.setVar.outputs.TAG }}
        docker build -t returnhelper/dotnet-builder:$version -t returnhelper/dotnet-builder:latest .
        docker push returnhelper/dotnet-builder:$version
        docker push returnhelper/dotnet-builder:latest
    - name: publish
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ env.RELEASE_VERSION }}
        body: |
          Release ${{ env.RELEASE_VERSION }}
        draft: false
        prerelease: false
