name: Build and push image to docker hub
on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-rc-*'
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: set var
      id: setVar
      run: |
        echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
        echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - uses: actions/checkout@v2
      with:
        ref: ${{ steps.setVar.outputs.TAG }}
    - name: Login
      run: |
        echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build and push
      run: |
        version=${{ steps.setVar.outputs.TAG }}
        docker build . -t returnhelper/dotnet-builder:$version
        docker push returnhelper/dotnet-builder:$version
    - name: publish
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ env.RELEASE_VERSION }}
        body: |
          Release ${{ env.RELEASE_VERSION }}
        draft: false
        prerelease: false
