name: Build and push image to docker hub
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login
      run: |
        echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build and push
      run: |
        version=${GITHUB_REF/refs\/tags\//}
        docker build . -t returnhelper/dotnet-builder:$version
        docker push returnhelper/dotnet-builder:$version
